### ISSUE TITLE
服务器坏了

### ISSUE THREAD

**Issue by zhao-yiqun** [svip-lab/SvipLab-ChatGPT-Web-Share#1]
@Jinpeng-Yu 服务器坏了好几天了，该修了

**Comment by Jinpeng-Yu** [comment]
从服务器刚挂的时候就已经在修了，但是目前为止所有针对该问题的解决方案都没办法解决该问题，请各位耐心等待

**Comment by Jinpeng-Yu** [comment]
@zhao-yiqun

**Comment by Jinpeng-Yu** [comment]
chatgpt web share 平台目前已可以正常使用
